wms-supply-problem-stg:
  extends: .integration_testing
  stage: inbound
  variables:
    SCHEDULE_MODE: inbound
    CHANNEL: wms-test-run-stg,wms-test-inbound
    REPORT_PROJECT_NAME: WMS-Supply-Problem
    TEST_FOLDER: tests/api/wms/supply_problem
    SERVICE: supply-problem
    PARALLEL_THREADS: 8
    RETRIES: 3
  timeout: 2h
