include:
  - local: '/.gitlab-ci.d/regression/templates/inbound'

regression test:
  allow_failure: true
  stage: post-deploy
  trigger:
    project: supply-chain-qa/manual-pipelines
    branch: 'master'
  variables:
    VERSION: ${CI_COMMIT_REF_SLUG}
  rules:
    - if: '$CI_PROJECT_NAME != "manual-pipelines" && $CI_COMMIT_BRANCH =~ /^(story|release|hotfix)/'
      when: manual
    - when: never
