collect_traces: False
project_path: ikarazanov/Autotest-project
credentials_file_name: config.env

team:
  service_one:
    address: https://restful-booker.herokuapp.com
  wiremock:
    address: https://wiremock-server:1234
  fsso:
    address: https://to-token:4321

db:
  db_one:
    credentials: "db_one"
